name: Auto merge PHPUnit
on:
  workflow_call:
    secrets: inherit 
jobs:
  dependabot_auto_merge_code_sniffer:
    uses: phpolar/github-workflows/.github/workflows/common-composer-dep-auto-merge.yml
    with:
      dependency-name: phpunit 
      composer-run: "ci:test"
